"$schema" = 'https://starship.rs/config-schema.json' # Editor completions

add_newline = true # Line between shell prompts

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[python]
python_binary = ['python', 'python3', 'python2']
pyenv_version_name = true
